### ISSUE TITLE
Update docs to indicate that `wagtail.contrib.settings` is required in `INSTALLED_APPS`

### ISSUE THREAD

**Issue by engineervix** [neon-jungle/wagtail-schema.org#11]
Thanks for this awesome package.

I encountered the following error while accessing the `/admin/` route:

```
django.urls.exceptions.NoReverseMatch: 'wagtailsettings' is not a registered namespace
```

After debugging and googling, I discovered that I needed to add `wagtail.contrib.settings` to `INSTALLED_APPS` to fix the problem. Additional reference: <https://github.com/chrisdev/django-wagtail-feeds/issues/28#issuecomment-270129087>

It would therefore be great to update the docs to mention this so that newcomers don't trip on the same problem. I'm happy to open a PR.

**Comment by seb-b** [comment]
thanks for pointing this out, I'm only 1 year late to adding it to the readme 😆
