### ISSUE TITLE
Update for Wagtail 4.0 Compatibility (BaseSiteSetting replacing BaseSetting)

### ISSUE THREAD

**Issue by dkirkham** [neon-jungle/wagtail-schema.org#13]
Wagtail 4.0 will start deprecating `wagtail.contrib.settings.models.BaseSetting` in favour of `wagtail.contrib.settings.models.BaseSiteSetting` or `wagtail.contrib.settings.models.BaseGenericSetting`. The to be deprecated class is used by wagtail-schema.org's `BaseLDSetting` at https://github.com/neon-jungle/wagtail-schema.org/blob/master/wagtailschemaorg/models.py#L22

Testing with Wagtail 4.0rc2 results in the following message:

```
.../site-packages/django/db/models/base.py:515: RemovedInWagtail50Warning: `wagtail.contrib.settings.models.BaseSetting` is obsolete and should be replaced by `wagtail.contrib.settings.models.BaseSiteSetting` or `wagtail.contrib.settings.models.BaseGenericSetting`
```

Release notes are at https://docs.wagtail.org/en/latest/releases/4.0.html#basesetting-model-replaced-by-basesitesetting

The solution might be to import into wagtailschemaorg/models.py `BaseSiteSetting`, and if that fails, fall back to `BaseSetting`.

**Comment by nickmoreton** [comment]
This change is included in: https://github.com/neon-jungle/wagtail-schema.org/pull/15

**Comment by dkirkham** [comment]
Thanks @nickmoreton, any idea when #15 will be merged and the package released to PyPi?

**Comment by nickmoreton** [comment]
> Thanks @nickmoreton, any idea when #15 will be merged and the package released to PyPi?

Sorry no but I'm sure it will be soon 👍

**Comment by dkirkham** [comment]
Thanks all.
